// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioEAI.Data;

#nullable disable

namespace PortfolioEAI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250709141732_LowFixAdminUser")]
    partial class LowFixAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserName");

                    b.HasKey("Id")
                        .HasName("IdAdminUser");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Company");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("EndDate");

                    b.Property<Guid>("IdAdminUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ImageUrl");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Position");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.HasKey("Id")
                        .HasName("IdExperience");

                    b.HasIndex("IdAdminUser");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<Guid?>("IdExperience")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.HasKey("Id")
                        .HasName("IdProject");

                    b.HasIndex("IdExperience");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdAdminUser")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("IdSkill");

                    b.HasIndex("IdAdminUser");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.AdminUser", b =>
                {
                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AdminUserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("AdminUserId");

                            b1.ToTable("AdminUsers");

                            b1.WithOwner()
                                .HasForeignKey("AdminUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Experience", b =>
                {
                    b.HasOne("PortfolioEAI.Domain.Entities.AdminUser", null)
                        .WithMany("Experiences")
                        .HasForeignKey("IdAdminUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Project", b =>
                {
                    b.HasOne("PortfolioEAI.Domain.Entities.Experience", null)
                        .WithMany("Projects")
                        .HasForeignKey("IdExperience")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.ObjectUrl", "Url", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Url");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Url")
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Skill", b =>
                {
                    b.HasOne("PortfolioEAI.Domain.Entities.AdminUser", null)
                        .WithMany("Skills")
                        .HasForeignKey("IdAdminUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.AdminUser", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Experience", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
