// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioEAI.Infrastructure.Persistance;

#nullable disable

namespace PortfolioEAI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Company");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Description");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("IdExperience")
                        .HasColumnType("char(36)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdExperience");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("IdSkill");

                    b.HasIndex("IdUser");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Experience", b =>
                {
                    b.HasOne("PortfolioEAI.Domain.Entities.User", null)
                        .WithMany("Experiences")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.StoredFile", "Image", b1 =>
                        {
                            b1.Property<Guid>("ExperienceId")
                                .HasColumnType("char(36)");

                            b1.Property<byte[]>("Content")
                                .IsRequired()
                                .HasColumnType("LONGBLOB");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)");

                            b1.Property<long>("Size")
                                .HasMaxLength(500)
                                .HasColumnType("bigint");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(127)
                                .HasColumnType("varchar(127)");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("ExperienceId");

                            b1.HasIndex("UploadedAt")
                                .IsUnique();

                            b1.ToTable("Experiences");

                            b1.WithOwner()
                                .HasForeignKey("ExperienceId");
                        });

                    b.Navigation("Image");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Project", b =>
                {
                    b.HasOne("PortfolioEAI.Domain.Entities.Experience", null)
                        .WithMany("Projects")
                        .HasForeignKey("IdExperience")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.StoredFile", "Image", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("char(36)");

                            b1.Property<byte[]>("Content")
                                .IsRequired()
                                .HasColumnType("LONGBLOB");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)");

                            b1.Property<long>("Size")
                                .HasMaxLength(500)
                                .HasColumnType("bigint");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(127)
                                .HasColumnType("varchar(127)");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("ProjectId");

                            b1.HasIndex("UploadedAt")
                                .IsUnique();

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.ObjectUrl", "Url", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Url");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Image");

                    b.Navigation("Url");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Skill", b =>
                {
                    b.HasOne("PortfolioEAI.Domain.Entities.User", null)
                        .WithMany("Skills")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.User", b =>
                {
                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.StoredFile", "ProfilePhoto", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<byte[]>("Content")
                                .IsRequired()
                                .HasColumnType("LONGBLOB");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)");

                            b1.Property<long>("Size")
                                .HasMaxLength(500)
                                .HasColumnType("bigint");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(127)
                                .HasColumnType("varchar(127)");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("UserId");

                            b1.HasIndex("UploadedAt")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("PortfolioEAI.Domain.Enums.Roles", "Role", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Role");

                            b1.HasKey("UserId");

                            b1.HasIndex("Id")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("HashValue")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.HasIndex("HashValue")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.PostalAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Country");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Street");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("ProfilePhoto");

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Experience", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.User", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
