// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioEAI.Data;

#nullable disable

namespace PortfolioEAI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250702111927_FixTableProjects")]
    partial class FixTableProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IdProject");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description")
                        .HasAnnotation("Relational:JsonPropertyName", "Description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrl")
                        .HasAnnotation("Relational:JsonPropertyName", "ImageUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title")
                        .HasAnnotation("Relational:JsonPropertyName", "Title");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PortfolioEAI.Domain.Entities.Project", b =>
                {
                    b.OwnsOne("PortfolioEAI.Domain.ValueObjects.ProjectUrl", "Url", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Url");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.HasAnnotation("Relational:JsonPropertyName", "Url");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Url")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
